<?php
$_templates_map = array(
   'Catalogs' => null,
   'Catalogs/EditForm'         => '/Catalogs/EditForm/EditForm.php',
   'Catalogs/EditForm/default' => '/Catalogs/EditForm/templates/default.php',
   'Catalogs/ItemForm'         => '/Catalogs/ItemForm/ItemForm.php',
   'Catalogs/ItemForm/default' => '/Catalogs/ItemForm/templates/default.php',
   'Catalogs/ListForm'         => '/Catalogs/ListForm/ListForm.php',
   'Catalogs/ListForm/default' => '/Catalogs/ListForm/templates/default.php',
   'Catalogs/ListForm/tree'    => '/Catalogs/ListForm/templates/tree.php',
   'Catalogs/TreeItem'         => '/Catalogs/TreeItem/TreeItem.php',
   'Catalogs/TreeItem/default' => '/Catalogs/TreeItem/templates/default.php',
   
   'Data_processors' => null,
   'Data_processors/ImportForm' => '/Data_processors/ImportForm/ImportForm.php',
   'Data_processors/ImportForm/default' => '/Data_processors/ImportForm/templates/default.php',
   
   'Documents' => null,
   'Documents/EditForm'         => '/Documents/EditForm/EditForm.php',
   'Documents/EditForm/default' => '/Documents/EditForm/templates/default.php',
   'Documents/ItemForm'         => '/Documents/ItemForm/ItemForm.php',
   'Documents/ItemForm/default' => '/Documents/ItemForm/templates/default.php',
   'Documents/ListForm'         => '/Documents/ListForm/ListForm.php',
   'Documents/ListForm/default' => '/Documents/ListForm/templates/default.php',
   
   'EditFormFields' => '/EditFormFields/EditFormFields.php',
   'EditFormFields/defaultBool'           => '/EditFormFields/templates/defaultBool.php',
   'EditFormFields/defaultDate'           => '/EditFormFields/templates/defaultDate.php',
   'EditFormFields/defaultDatetime'       => '/EditFormFields/templates/defaultDatetime.php',
   'EditFormFields/defaultEnum'           => '/EditFormFields/templates/defaultEnum.php',
   'EditFormFields/defaultFile'           => '/EditFormFields/templates/defaultFile.php',
   'EditFormFields/defaultFloat'          => '/EditFormFields/templates/defaultFloat.php',
   'EditFormFields/defaultInt'            => '/EditFormFields/templates/defaultInt.php',
   'EditFormFields/defaultOwnerReference' => '/EditFormFields/templates/defaultOwnerReference.php',
   'EditFormFields/defaultPassword'       => '/EditFormFields/templates/defaultPassword.php',
   'EditFormFields/defaultReference'      => '/EditFormFields/templates/defaultReference.php',
   'EditFormFields/defaultString'         => '/EditFormFields/templates/defaultString.php',
   
   'Information_registry' => null,
   'Information_registry/EditForm'         => '/Information_registry/EditForm/EditForm.php',
   'Information_registry/EditForm/default' => '/Information_registry/EditForm/templates/default.php',
   'Information_registry/ItemForm'         => '/Information_registry/ItemForm/ItemForm.php',
   'Information_registry/ItemForm/default' => '/Information_registry/ItemForm/templates/default.php',
   'Information_registry/ListForm'         => '/Information_registry/ListForm/ListForm.php',
   'Information_registry/ListForm/default' => '/Information_registry/ListForm/templates/default.php',
   
   'ItemFormFields' => '/ItemFormFields/ItemFormFields.php',
   'ItemFormFields/defaultBool'      => '/ItemFormFields/templates/defaultBool.php',
   'ItemFormFields/defaultDate'      => '/ItemFormFields/templates/defaultDate.php',
   'ItemFormFields/defaultDatetime'  => '/ItemFormFields/templates/defaultDatetime.php',
   'ItemFormFields/defaultEnum'      => '/ItemFormFields/templates/defaultEnum.php',
   'ItemFormFields/defaultFloat'     => '/ItemFormFields/templates/defaultFloat.php',
   'ItemFormFields/defaultInt'       => '/ItemFormFields/templates/defaultInt.php',
   'ItemFormFields/defaultReference' => '/ItemFormFields/templates/defaultReference.php',
   'ItemFormFields/defaultString'    => '/ItemFormFields/templates/defaultString.php',
   
   'ListFormFields' => '/ListFormFields/ListFormFields.php',
   'ListFormFields/defaultBool'      => '/ListFormFields/templates/defaultBool.php',
   'ListFormFields/defaultDate'      => '/ListFormFields/templates/defaultDate.php',
   'ListFormFields/defaultDatetime'  => '/ListFormFields/templates/defaultDatetime.php',
   'ListFormFields/defaultEnum'      => '/ListFormFields/templates/defaultEnum.php',
   'ListFormFields/defaultFloat'     => '/ListFormFields/templates/defaultFloat.php',
   'ListFormFields/defaultInt'       => '/ListFormFields/templates/defaultInt.php',
   'ListFormFields/defaultReference' => '/ListFormFields/templates/defaultReference.php',
   'ListFormFields/defaultString'    => '/ListFormFields/templates/defaultString.php',
   
   'MainTemplates' => null,
   'MainTemplates/default' => '/MainTemplates/default.php',
   
   'Pagination' => '/Pagination/Pagination.php',
   'Pagination/default' => '/Pagination/templates/default.php',
   
   'Reports' => null,
   'Reports/ReportForm' => '/Reports/ReportForm/ReportForm.php',
   'Reports/ReportForm/default' => '/Reports/ReportForm/templates/default.php',
   
   'Tabulars' => null,
   'Tabulars/EditForm'            => '/Tabulars/EditForm/EditForm.php',
   'Tabulars/EditForm/default'    => '/Tabulars/EditForm/templates/default.php',
   'Tabulars/ItemForm'            => '/Tabulars/ItemForm/ItemForm.php',
   'Tabulars/ItemForm/default'    => '/Tabulars/ItemForm/templates/default.php',
   'Tabulars/TabularItem'         => '/Tabulars/TabularItem/TabularItem.php',
   'Tabulars/TabularItem/default' => '/Tabulars/TabularItem/templates/default.php',
   
   'CustomForm' => '/CustomForm/CustomForm.php',
   
   'Constants/EditForm' => '/Constants/EditForm.php',

   'DeleteMarkedForDeletion/DeletionForm' => '/DeleteMarkedForDeletion/DeletionForm.php'
);
