<?php
$_templates_map = array(
   'Template:Entities/Catalogs' => null,
   'Template:Entities/Catalogs/EditForm' => '/Catalogs/EditForm/EditForm.php',
   'Template:Entities/Catalogs/EditForm/default' => '/Catalogs/EditForm/templates/default.php',
   'Template:Entities/Catalogs/EditForm/custom'  => '/Catalogs/EditForm/templates/custom.php',
   'Template:Entities/Catalogs/ItemForm' => '/Catalogs/ItemForm/ItemForm.php',
   'Template:Entities/Catalogs/ItemForm/default' => '/Catalogs/ItemForm/templates/default.php',
   'Template:Entities/Catalogs/ListForm' => '/Catalogs/ListForm/ListForm.php',
   'Template:Entities/Catalogs/ListForm/default' => '/Catalogs/ListForm/templates/default.php',
   
   'Template:Entities/Data_processors' => null,
   'Template:Entities/Data_processors/ImportForm' => '/Data_processors/ImportForm/ImportForm.php',
   'Template:Entities/Data_processors/ImportForm/default' => '/Data_processors/ImportForm/templates/default.php',
   
   'Template:Entities/Documents' => null,
   'Template:Entities/Documents/EditForm' => '/Documents/EditForm/EditForm.php',
   'Template:Entities/Documents/EditForm/default' => '/Documents/EditForm/templates/default.php',
   'Template:Entities/Documents/ItemForm' => '/Documents/ItemForm/ItemForm.php',
   'Template:Entities/Documents/ItemForm/default' => '/Documents/ItemForm/templates/default.php',
   'Template:Entities/Documents/ListForm' => '/Documents/ListForm/ListForm.php',
   'Template:Entities/Documents/ListForm/default' => '/Documents/ListForm/templates/default.php',
   
   'Template:Entities/EditFormFields' => '/EditFormFields/EditFormFields.php',
   'Template:Entities/EditFormFields/defaultDate'      => '/EditFormFields/templates/defaultDate',
   'Template:Entities/EditFormFields/defaultDatetime'  => '/EditFormFields/templates/defaultDatetime',
   'Template:Entities/EditFormFields/defaultEnum'      => '/EditFormFields/templates/defaultEnum',
   'Template:Entities/EditFormFields/defaultFloat'     => '/EditFormFields/templates/defaultFloat',
   'Template:Entities/EditFormFields/defaultInt'       => '/EditFormFields/templates/defaultInt',
   'Template:Entities/EditFormFields/defaultPassword'  => '/EditFormFields/templates/defaultPassword',
   'Template:Entities/EditFormFields/defaultReference' => '/EditFormFields/templates/defaultReference',
   'Template:Entities/EditFormFields/defaultString'    => '/EditFormFields/templates/defaultString',
   
   'Template:Entities/Information_registry' => null,
   'Template:Entities/Information_registry/ListForm' => '/Information_registry/ListForm.php',
   'Template:Entities/Information_registry/ListForm/default' => '/Information_registry/ListForm/templates/default.php',
   
   'Template:Entities/ItemFormFields' => '/ItemFormFields/ItemFormFields.php',
   'Template:Entities/ItemFormFields/defaultDate'      => '/ItemFormFields/templates/defaultDate',
   'Template:Entities/ItemFormFields/defaultDatetime'  => '/ItemFormFields/templates/defaultDatetime',
   'Template:Entities/ItemFormFields/defaultEnum'      => '/ItemFormFields/templates/defaultEnum',
   'Template:Entities/ItemFormFields/defaultFloat'     => '/ItemFormFields/templates/defaultFloat',
   'Template:Entities/ItemFormFields/defaultInt'       => '/ItemFormFields/templates/defaultInt',
   'Template:Entities/ItemFormFields/defaultPassword'  => '/ItemFormFields/templates/defaultPassword',
   'Template:Entities/ItemFormFields/defaultReference' => '/ItemFormFields/templates/defaultReference',
   'Template:Entities/ItemFormFields/defaultString'    => '/ItemFormFields/templates/defaultString',
   
   'Template:Entities/ListFormFields' => '/ListFormFields/ListFormFields.php',
   'Template:Entities/ListFormFields/defaultDate'      => '/ListFormFields/templates/defaultDate',
   'Template:Entities/ListFormFields/defaultDatetime'  => '/ListFormFields/templates/defaultDatetime',
   'Template:Entities/ListFormFields/defaultEnum'      => '/ListFormFields/templates/defaultEnum',
   'Template:Entities/ListFormFields/defaultFloat'     => '/ListFormFields/templates/defaultFloat',
   'Template:Entities/ListFormFields/defaultInt'       => '/ListFormFields/templates/defaultInt',
   'Template:Entities/ListFormFields/defaultPassword'  => '/ListFormFields/templates/defaultPassword',
   'Template:Entities/ListFormFields/defaultReference' => '/ListFormFields/templates/defaultReference',
   'Template:Entities/ListFormFields/defaultString'    => '/ListFormFields/templates/defaultString',
   
   'Template:Entities/MainTemplates' => null,
   'Template:Entities/MainTemplates/default' => '/MainTemplates/default.php',
   
   'Template:Entities/Pagination' => '/Pagination/Pagination.php',
   'Template:Entities/Pagination/default' => '/Pagination/templates/default.php',
   
   'Template:Entities/Reports' => null,
   'Template:Entities/Reports/ReportForm' => '/Reports/ReportForm.php',
   'Template:Entities/Reports/ReportForm/default' => '/Reports/ReportForm/templates/default.php',
   
   'Template:Entities/Tabulars' => null,
   'Template:Entities/Tabulars/EditForm' => '/Tabulars/EditForm/EditForm.php',
   'Template:Entities/Tabulars/EditForm/default' => '/Tabulars/EditForm/templates/default.php',
   'Template:Entities/Tabulars/ItemForm' => '/Tabulars/ItemForm/ItemForm.php',
   'Template:Entities/Tabulars/ItemForm/default' => '/Tabulars/ItemForm/templates/default.php',
   'Template:Entities/Tabulars/TabularItem' => '/Tabulars/TabularItem/TabularItem.php',
   'Template:Entities/Tabulars/TabularItem/default' => '/Tabulars/TabularItem/templates/default.php',
);
